# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

TEST_DEVICE="iPhone 13"
TEST_IOS_VERSION="15.0"

PROJECT_SCHEME="MobileExercise"
DERIVED_DATA_PATH='./.DerivedData'

default_platform(:ios)

platform :ios do
  desc "Test Swift Package"
  lane :test do
    scan(
      package_path: '.',
      scheme: PROJECT_SCHEME,
      clean: false,
      device: TEST_DEVICE,
      code_coverage: true,
      derived_data_path: DERIVED_DATA_PATH,
      cloned_source_packages_path: './.DerivedData/SourcePackages/checkouts'
    )
  end
end
